/*
 * AssemblyLine — Sketchfab model by MD.Jobair Hossain
 * License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
 * Source: https://sketchfab.com/3d-models/assembly-line-7bc390083e2e4abc88f7013948b0791c
 *
 * Auto-generated by gltfjsx, then cleaned up:
 *   - Fixed model path to /models/assembly_line.glb
 *   - Renamed component from Model → AssemblyLine
 *   - Removed undefined GLTFAction type
 *   - Added name props to each mesh for raycasting
 *   - Centred the model origin (offset position cleared)
 *   - Added ref-based animation hook for belt/moving parts
 *
 * Node map (8 meshes, all in one group — 3ds Max multi-material export):
 *   Material_12 — frame / structural steel (dark grey)
 *   Material_1  — belt / conveyor surface
 *   Material_2  — rollers / shafts
 *   Material_11 — guard rails / safety covers
 *   Material_20 — motor housing
 *   Material_19 — floor mounting / base plates
 *   Material_24 — labels / warning markings
 *   Material_9  — electrical conduit / wiring
 *
 * NOTE: Material assignments are inferred from colour inspection.
 * Verify visually in the browser and update the map above.
 */

'use client'

import * as THREE from 'three'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useGameStore } from '@/stores/gameStore'

// Point the Draco decoder at our local WASM files (works offline on lab machines).
// Must be called before any useGLTF() that loads a Draco-compressed model.
useGLTF.setDecoderPath('/draco/')

type GLTFResult = GLTF & {
  nodes: {
    ['assembly_Material_#12_0']: THREE.Mesh
    ['assembly_Material_#1_0']:  THREE.Mesh
    ['assembly_Material_#2_0']:  THREE.Mesh
    ['assembly_Material_#11_0']: THREE.Mesh
    ['assembly_Material_#20_0']: THREE.Mesh
    ['assembly_Material_#19_0']: THREE.Mesh
    ['assembly_Material_#24_0']: THREE.Mesh
    ['assembly_Material_#9_0']:  THREE.Mesh
  }
  materials: {
    Material_12: THREE.MeshStandardMaterial
    Material_1:  THREE.MeshStandardMaterial
    Material_2:  THREE.MeshStandardMaterial
    Material_11: THREE.MeshStandardMaterial
    Material_20: THREE.MeshStandardMaterial
    Material_19: THREE.MeshStandardMaterial
    Material_24: THREE.MeshStandardMaterial
    Material_9:  THREE.MeshStandardMaterial
  }
}

// Pre-allocated — never new inside useFrame
const _beltOffset = new THREE.Vector2()

export function AssemblyLine(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/assembly_line.glb') as GLTFResult

  // Belt mesh ref — animated when Q0.0 (motor run) is true
  const beltRef = useRef<THREE.Mesh>(null)
  const isRunning = useGameStore(s => s.tags['Q0.0']?.value ?? false)

  useFrame((_, delta) => {
    if (!isRunning || !beltRef.current) return
    const mat = beltRef.current.material as THREE.MeshStandardMaterial
    if (mat.map) {
      mat.map.offset.x += delta * 0.4 // belt scroll speed
    }
  })

  return (
    <group {...props} dispose={null}>
      {/* Scale 0.025: model was authored in centimetres (3ds Max default).
          Position offset cleared — place the group via props.position instead. */}
      <group scale={0.025}>
        <group position={[0, 35.662, 0]}>
          {/* Internal offset from the original 3ds Max scene origin */}
          <group position={[181.245, -1.606, -145.916]}>
            {/* Frame / structural steel */}
            <mesh
              name="assembly_frame"
              geometry={nodes['assembly_Material_#12_0'].geometry}
              material={materials.Material_12}
              castShadow
              receiveShadow
            />
            {/* Belt / conveyor surface — animated when motor is running */}
            <mesh
              ref={beltRef}
              name="assembly_belt"
              geometry={nodes['assembly_Material_#1_0'].geometry}
              material={materials.Material_1}
              receiveShadow
            />
            {/* Rollers / shafts */}
            <mesh
              name="assembly_rollers"
              geometry={nodes['assembly_Material_#2_0'].geometry}
              material={materials.Material_2}
              castShadow
            />
            {/* Guard rails / safety covers */}
            <mesh
              name="assembly_guards"
              geometry={nodes['assembly_Material_#11_0'].geometry}
              material={materials.Material_11}
              castShadow
            />
            {/* Motor housing — named for raycasting */}
            <mesh
              name="conveyor_motor"
              geometry={nodes['assembly_Material_#20_0'].geometry}
              material={materials.Material_20}
              castShadow
            />
            {/* Base plates / floor mounting */}
            <mesh
              name="assembly_base"
              geometry={nodes['assembly_Material_#19_0'].geometry}
              material={materials.Material_19}
              receiveShadow
            />
            {/* Warning labels / markings */}
            <mesh
              name="assembly_labels"
              geometry={nodes['assembly_Material_#24_0'].geometry}
              material={materials.Material_24}
            />
            {/* Electrical conduit / wiring */}
            <mesh
              name="assembly_conduit"
              geometry={nodes['assembly_Material_#9_0'].geometry}
              material={materials.Material_9}
              castShadow
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/assembly_line.glb')
